log_message: "Org type mapping"
file_prefix: "org_type"
code_key: "#org +type +code +v_hrinfo"
name_key: "#org +type +preferred"

datasetinfo:
  dataset: "organization-types-beta"
  resource: "Organization Types (Beta) - CSV"
  format: "csv"
  headers: 2

extra_entries:
  "501": "Civil Society"
  "502": "Observer"
  "503": "Development Programme"
  "504": "Local NGO"

initial_lookup:
  academy: "431"
  agence un: "447"
  agence des nations unies: "447"
  agence du systeme des nations unies: "447"
  autre type: "443"
  civile society: "501"
  cooperation internationale: "501"
  croix rouge: "445"
  donantes: "433"
  entite gouvernementale: "435"
  gouv: "435"
  gouvernement: "435"
  gov: "435"
  government agency: "435"
  gobierno: "435"
  govt: "435"
  iglesia grupo religioso: "446"
  ingo: "437"
  institution etatique: "435"
  institución publica: "435"
  international government: "435"
  international institution: "438"
  international ngos: "437"
  local ngo: "504"
  mouv cr: "445"
  mouvement croix rouge: "445"
  mouvement de la croix rouge: "445"
  movimiento de la cruz roja media luna roja: "445"
  national local ngo: "441"
  nations unies: "447"
  naciones unidas: "447"
  nngo: "441"
  observer: "502"
  ong int: "437"
  ong internacional: "437"
  ong internationale: "437"
  ong local: "504"
  ong nat: "441"
  ong national: "441"
  ong nacional: "441"
  ong nationale: "441"
  organisation des nations unies: "447"
  organismo internacional: "438"
  others: "443"
  otro: "443"
  programme de developpement: "503"
  red cross: "445"
  red cross movement: "445"
  red cross mvt: "445"
  red cross and red crescent movement: "445"
  religious group: "446"
  religious organization: "446"
  service etatique: "435"
  sociedad civil: "501"
  societe civile: "501"
  un: "447"
  un agency: "447"
  un agencies: "447"
